# Generated by Django 2.1.2 on 2018-10-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fechamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
