# Generated by Django 2.1.2 on 2018-10-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181023_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='total',
        ),
    ]
