# Generated by Django 2.1.2 on 2018-10-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_compra_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='campista',
            new_name='nome',
        ),
    ]
