# Generated by Django 2.1.2 on 2018-10-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181024_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='quantidade',
            new_name='qntd',
        ),
    ]
