# Generated by Django 2.1.2 on 2018-10-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181025_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='produto',
            new_name='nome',
        ),
    ]
